### ISSUE TITLE
Update repo description and add link to PyPI 

### ISSUE THREAD

**Issue by bittner** [mdgart/sentrylogs#25]
@mdgart Mauro, could you please:

1. update the repository description here on GitHub, so that it matches the current module docstring?

> Send logs from Nginx and other applications to Sentry.

2. and also add the link to PyPI next to it: https://pypi.python.org/pypi/SentryLogs

I don't have the required admin permissions on your repository.

Note that I've released version 0.3.0 today still with the old, slightly misleading package description.

**Comment by mdgart** [comment]
Done
