### ISSUE TITLE
Publish release 0.4.0

### ISSUE THREAD

**Issue by bittner** [mdgart/sentrylogs#30]
We should push a new release to [PyPI](https://pypi.org/project/SentryLogs/).

- [x] Update changelog (fixed with commit 53e7c7a)
- [x] Bump version number (fixed with commit 53e7c7a)
- [x] Run `./setup.py sdist upload`
- [x] Tag master branch `git tag 0.4.0`

**Comment by mdgart** [comment]
This is done
