### ISSUE TITLE
Improve NGINX log parsing

### ISSUE THREAD

**Issue by madsmtm** [mdgart/sentrylogs#32]
The NGINX log parsing is quite rudimentary, it would be nice if we could expand it to be more robust, and for example, properly extract the log level. See [this stackoverflow answer](https://stackoverflow.com/a/26125951) for more information on how the format is structured.

**Comment by bittner** [comment]
Do you want to try a PR on this? I'm sure this would be super-welcome!

**Comment by mdgart** [comment]
Sure!

**Comment by Siecje** [comment]
With the log level, the message to sentry can include the log level.

**Comment by bittner** [comment]
Providing a PR should not be too difficult. It all happens in the [parsers.nginx](https://github.com/mdgart/sentrylogs/blob/master/sentrylogs/parsers/nginx.py#L26-L41) module.

**Comment by Siecje** [comment]
Can this be closed now that #36 has been merged?

**Comment by mdgart** [comment]
Done
