### ISSUE TITLE
Please, upload the most recent version to PyPi

### ISSUE THREAD

**Issue by nagyv** [mdgart/sentrylogs#6]

**Comment by bittner** [comment]
Still working on this project, @nagyv? I see you're one of the package owners on PyPI, but I don't see a fork of this project [in your GitHub profile](https://github.com/nagyv?tab=repositories).

**Comment by bittner** [comment]
Good news!

I've compared the uploaded [version 0.1.0 on PyPI](https://pypi.python.org/pypi/SentryLogs/0.1.0) with commit 3d3a8db, and it turns out the Python sources are identical. Hence the code from 03-Jul-2013 had been taken and uploaded as "version 0.1.0" a year later, on 25-Jul-2014.
