### ISSUE TITLE
Is this the repo for PyPI's SentryLogs package?

### ISSUE THREAD

**Issue by bittner** [mdgart/sentrylogs#7]
I was looking for a way to push errors from error logs (e.g. nginx, postgres, mysql, redis, supervisor) to Sentry. This way I've found the [SentryLogs package](https://pypi.python.org/pypi/SentryLogs) on PyPI.

## Just Wondering ...

However, the version number on PyPI is 0.1.0, and it's only 0.0.9 [in this repository](https://github.com/mdgart/sentrylogs/blob/master/setup.py#L5). So, is this the official repository (and the latest version was uploaded but not put under version control)?

## PyPI Package Needs Fixing

If this _is_ the official repo, a link on PyPI (`url` [keyword in setup](https://github.com/mdgart/sentrylogs/blob/master/setup.py#L10)) back _to the source code_ repository would be awesome.

**Comment by mdgart** [comment]
This is the official repository, I don't have the version that is currently on PyPI anymore, but even if there are differences between the two they are probably very minimal. I'm not maintaining this project anymore, but if you want to contribute I'm happy to help.

**Comment by bittner** [comment]
I'm going to work on this on my fork, and place one or more PRs probably today.

There is no license in this repo (the [LICENSE file](https://github.com/mdgart/sentrylogs/blob/master/LICENSE.txt) is empty). Do you have a preference for one? It may make sense to use the one [Sentry](https://pypi.python.org/pypi/sentry) is also using ([BSD](https://github.com/getsentry/sentry/blob/master/LICENSE), [3-clause](https://en.wikipedia.org/wiki/BSD_licenses#3-clause_license_.28.22Revised_BSD_License.22.2C_.22New_BSD_License.22.2C_or_.22Modified_BSD_License.22.29) most probably, [classifier for setuptools](https://pypi.python.org/pypi?%3Aaction=list_classifiers) `License :: OSI Approved :: BSD License`).

**Comment by mdgart** [comment]
Sounds good

2016-06-07 8:19 GMT-07:00 Peter Bittner <notifications@github.com>:

**Comment by bittner** [comment]
I've opened PR #10 to address the shortcomings mentioned here, and some mentioned in issue #8.

Thanks for merging!
